version: '2'

services:
  nginx:
    image: nginx:1.14
    container_name: kodexplorer-nginx
    ports:
      - '8063:8063'
    networks:
      - proxynet
      - internal
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './var/www/html:/var/www/html'
    labels:
      traefik.enable: 'true'
      traefik.frontend.redirect.entryPoint: 'https'
      traefik.frontend.rule: 'Host:my.host.tld'
      traefik.port: 8063
      traefik.docker.network: 'proxynet'

  php-fpm:
    image: martin-juul/kodexplorer-for-docker:php-fpm7.1
    container_name: kodexplorer-phpfpm
    networks:
      - internal
    volumes:
      - './data/site:/var/www/html'
      - './data/share:/data'

networks:
  proxynet:
    external: true
  internal: